eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
logging:
  level:
    com:
      netflix:
        discovery: OFF
        eureka: OFF
server:
  port: 8761